name: baby-tritium-transport-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - openmc
  - python-gmsh
  - matplotlib
  - festim=2.0a0
  - pip
  - pip:
    - git+https://github.com/LIBRA-project/libra-toolbox@v0.5
    - openmc-data-downloader